name: Refresh Cookies

on:
  schedule:
    - cron: "*/10 * * * *"  # chạy mỗi 10 phút
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios tough-cookie axios-cookiejar-support p-queue https-proxy-agent

      - name: Run refresh multi-thread + proxy
        run: node refresh.js

      - name: Commit updated cookies
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@github.com"
          git add cookies.json
          git commit -m "Auto refresh cookies at $(date)" || echo "No changes"
          git push
